server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        add_header Cache-Control "no-store";
        try_files $uri /index.html;
    }

    # Проксирование корневых API-запросов (/guest, /login, /me и т.д.)
    location ~ ^/(guest|login|me|register|delete|translate|save_word|any_word|frontend-log|update_word|delete_word|delete_set|move_word|rename_set|get_word|get_better_translation|get_synonyms|get_antonyms|get_sentences|anyWord|get_sets|get_words|get_text|get_voice|new_settings|get_settings|update_settings)($|/) {
        proxy_pass http://wordchain-backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
