# services:
#   db:
#     image: postgres:16-alpine
#     container_name: wordchain-db
#     environment:
#       POSTGRES_DB: wordchain
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 1234
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     ports:
#       - "5440:5432"

#   backend:
#     build:
#       context: ./backend
#     container_name: wordchain-backend
#     depends_on:
#       - db
#     env_file:
#       - ./backend/.env
    

#   frontend:
#     build:
#       context: ./frontend
#     container_name: wordchain-frontend
#     depends_on:
#       - backend
#     ports:
#       - "8000:80"

# volumes:
#   pgdata:


services:
  db:
    image: postgres:16-alpine
    container_name: wordchain-db
    environment:
      POSTGRES_DB: wordchain
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5440:5432

  redis:
    image: redis:7-alpine
    container_name: wordchain-redis


  backend:
    build:
      context: ./backend
    container_name: wordchain-backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
        ./backend/.env


  frontend:
    build:
      context: ./frontend
    container_name: wordchain-frontend
    depends_on:
      - backend
    ports:
      - 8000:80

volumes:
  pgdata:
