[tool.poetry]
name = "wordchain"
version = "0.1.0"
description = ""
authors = ["Sergey Budaev <sergeybudaev999@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
fastapi = "^0.127.0"
uvicorn = "^0.40.0"
loguru = "^0.7.3"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

