[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Sergey Budaev <sergeybudaev999@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
fastapi = "^0.127.0"
uvicorn = "^0.40.0"
sqlalchemy = "^2.0.45"
asyncpg = "^0.31.0"
psycopg2-binary = "^2.9.11"
python-jose = "^3.5.0"
pydantic-settings = "^2.12.0"
httpx = "^0.28.1"
redis = "^7.1.0"
passlib = "^1.7.4"
alembic = "^1.18.4"
loguru = "^0.7.3"
openai = "1.59.6"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
